/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modelo;

import java.awt.Color;
import java.awt.Desktop;
import java.util.Observable;
import java.util.Observer;

import java.awt.Graphics;
import java.awt.GridLayout;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmMenu extends javax.swing.JFrame implements Observer {

    CronometroHilo hilo1;
    private ArrayList<JButton> listaBotones = new ArrayList<>();
    private ArrayList<JButton> listaBotonesProducc = new ArrayList<>();
    private ArrayList<JButton> listaBotonesEmpaquetado = new ArrayList<>();
    private ArrayList<JButton> listaBotonesSalida = new ArrayList<>();

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);

        CronometroHilo hilo1 = new CronometroHilo(0, 0, 0);
        hilo1.addObserver(this);
        Thread t = new Thread(hilo1);
        t.start();
        //iniciarlizar el cronocmetro
        HiloInicio hilo2 = new HiloInicio(btnHilo1, JLRepeticiones);
        hilo2.start();

        crearBotonesInventarios();
        crearBorotonesProduccion();
        crearBorotonesEmpaquetado();
        crearBorotonesSalida();
        //iniciarHiloInventario();

        HiloFinal hilo12 = new HiloFinal(btnHiloFinal, JLFinal, btnRegresar, btnRepor, hilo1);
        hilo12.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnRepor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbTiempo = new javax.swing.JLabel();
        btnHilo1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        JLRepeticiones = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPProduccion = new javax.swing.JPanel();
        jPInventario = new javax.swing.JPanel();
        jLTiempoProduccion = new javax.swing.JLabel();
        JlConteoInventario = new javax.swing.JLabel();
        jPEmpaquetado = new javax.swing.JPanel();
        jLEmpaqueteTiem = new javax.swing.JLabel();
        jPSalida = new javax.swing.JPanel();
        jLSaliadTiem = new javax.swing.JLabel();
        JLFinal = new javax.swing.JLabel();
        btnHiloFinal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnRegresar.setBackground(new java.awt.Color(153, 204, 255));
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.setEnabled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnRepor.setBackground(new java.awt.Color(153, 204, 255));
        btnRepor.setForeground(new java.awt.Color(0, 0, 0));
        btnRepor.setText("Reporte");
        btnRepor.setEnabled(false);
        btnRepor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("Tiempo: ");

        jbTiempo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N

        btnHilo1.setBackground(new java.awt.Color(255, 255, 255));
        btnHilo1.setForeground(new java.awt.Color(255, 255, 255));
        btnHilo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnHilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHilo1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Inicio:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Final");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Producción");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Inventario");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Salida");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Empaquetado");

        jPProduccion.setBackground(new java.awt.Color(255, 255, 255));
        jPProduccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPProduccion.setForeground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout jPProduccionLayout = new javax.swing.GroupLayout(jPProduccion);
        jPProduccion.setLayout(jPProduccionLayout);
        jPProduccionLayout.setHorizontalGroup(
            jPProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPProduccionLayout.setVerticalGroup(
            jPProduccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        jPInventario.setBackground(new java.awt.Color(255, 255, 255));
        jPInventario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153), 2));
        jPInventario.setForeground(new java.awt.Color(255, 255, 255));
        jPInventario.setPreferredSize(new java.awt.Dimension(370, 225));
        jPInventario.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPInventarioLayout = new javax.swing.GroupLayout(jPInventario);
        jPInventario.setLayout(jPInventarioLayout);
        jPInventarioLayout.setHorizontalGroup(
            jPInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPInventarioLayout.setVerticalGroup(
            jPInventarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        jPEmpaquetado.setBackground(new java.awt.Color(255, 255, 255));
        jPEmpaquetado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPEmpaquetado.setForeground(new java.awt.Color(102, 0, 102));
        jPEmpaquetado.setPreferredSize(new java.awt.Dimension(370, 225));

        javax.swing.GroupLayout jPEmpaquetadoLayout = new javax.swing.GroupLayout(jPEmpaquetado);
        jPEmpaquetado.setLayout(jPEmpaquetadoLayout);
        jPEmpaquetadoLayout.setHorizontalGroup(
            jPEmpaquetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPEmpaquetadoLayout.setVerticalGroup(
            jPEmpaquetadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        jPSalida.setBackground(new java.awt.Color(255, 255, 255));
        jPSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPSalida.setForeground(new java.awt.Color(102, 0, 102));
        jPSalida.setPreferredSize(new java.awt.Dimension(370, 225));

        javax.swing.GroupLayout jPSalidaLayout = new javax.swing.GroupLayout(jPSalida);
        jPSalida.setLayout(jPSalidaLayout);
        jPSalidaLayout.setHorizontalGroup(
            jPSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPSalidaLayout.setVerticalGroup(
            jPSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 221, Short.MAX_VALUE)
        );

        btnHiloFinal.setBackground(new java.awt.Color(255, 255, 255));
        btnHiloFinal.setForeground(new java.awt.Color(255, 255, 255));
        btnHiloFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnHiloFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHiloFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(191, 191, 191)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRepor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(228, 228, 228)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLSaliadTiem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btnHiloFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLEmpaqueteTiem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLTiempoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(JlConteoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(149, 149, 149)
                                        .addComponent(btnHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JLRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnRepor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTiempoProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEmpaqueteTiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addComponent(btnHiloFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JLRepeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHilo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPEmpaquetado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(133, 133, 133)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(JlConteoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLSaliadTiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(104, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:

        FrmMenuInicial mn = new FrmMenuInicial();
        mn.registros.clear();
        mn.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnHilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHilo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHilo1ActionPerformed

    private void btnHiloFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHiloFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHiloFinalActionPerformed

    private void btnReporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporActionPerformed
        // TODO add your handling code here:
        FrmMenuInicial menu = new FrmMenuInicial();
        StringBuilder htmlCodigo = new StringBuilder();
//obtener dato de inventarios
        int inventarioCosto = Integer.parseInt(menu.registros.get(0).getCosto());
        int inventarioTiempo = Integer.parseInt(menu.registros.get(0).getTiempo());
        int totalCostoInvetario = inventarioCosto * inventarioTiempo * 30;
//obtener dato de produccion
        int produccionCosto = Integer.parseInt(menu.registros.get(1).getCosto());
        int produccionTiempo = Integer.parseInt(menu.registros.get(1).getTiempo());
        int totalCostoProduccion = produccionCosto * produccionTiempo * 30;
//obtener dato de  empaquetado
        int empaquetadoCosto = Integer.parseInt(menu.registros.get(2).getCosto());
        int empaquetadoTiempo = Integer.parseInt(menu.registros.get(2).getTiempo());
        int totalCostoEmpaquetado = empaquetadoCosto * empaquetadoTiempo * 30;
//obtener dato de salida
        int salidCosto = Integer.parseInt(menu.registros.get(3).getCosto());
        int salidaTiempo = Integer.parseInt(menu.registros.get(3).getTiempo());
        int totalCostoSalida = salidCosto * salidaTiempo * 30;

        //total
        int totalSumatorio = totalCostoInvetario + totalCostoProduccion + totalCostoEmpaquetado + totalCostoSalida;

        htmlCodigo.append("<!DOCTYPE html>");
        htmlCodigo.append("<html lang=\"en\">");
        htmlCodigo.append("<head>");
        htmlCodigo.append(" <meta charset=\"UTF-8\">");
        htmlCodigo.append("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">");
        htmlCodigo.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
        htmlCodigo.append("<title>Reporte</title>");
        htmlCodigo.append("</head>");
        htmlCodigo.append("<h1>Reporte de costo</h1>");
        htmlCodigo.append("<center>");
        htmlCodigo.append("<table border=\"1\">");
        htmlCodigo.append("<thead>");
        htmlCodigo.append("<tr>");
        htmlCodigo.append("<th style=\"background-color: #4372FF ;\">Sector</th>");
        htmlCodigo.append("<th style=\"background-color: #4372FF ;\">costo de produccion</th>");
        htmlCodigo.append("<th style=\"background-color: #4372FF ;\">tiempo de produccion</th>");
        htmlCodigo.append("<th style=\"background-color: #4372FF ;\">materia prima</th>");
        htmlCodigo.append("<th style=\"background-color: #4372FF ;\">total</th>");
        htmlCodigo.append("</tr>");
        htmlCodigo.append("</thead>");
        htmlCodigo.append("<body>");
        htmlCodigo.append("<tr>");
        htmlCodigo.append("<td>Inventario</td>");
        htmlCodigo.append("<td>" + inventarioCosto + "</td>");
        htmlCodigo.append("<td>" + inventarioTiempo + "</td>");
        htmlCodigo.append("<td>30</td>");
        htmlCodigo.append("<td>" + totalCostoInvetario + "</td>");
        htmlCodigo.append("</tr>");
        htmlCodigo.append("<tr>");
        htmlCodigo.append("<td>Produccion</td>");
        htmlCodigo.append("<td>" + produccionCosto + " </td>");
        htmlCodigo.append("<td>" + produccionTiempo + "</td>");
        htmlCodigo.append("<td>30</td>");
        htmlCodigo.append("<td>" + totalCostoProduccion + "</td>");
        htmlCodigo.append("</tr>");
        htmlCodigo.append("<tr>");
        htmlCodigo.append("<td>Empaquetado</td>");
        htmlCodigo.append("<td>" + empaquetadoCosto + "</td>");
        htmlCodigo.append("<td>" + empaquetadoTiempo + "</td>");
        htmlCodigo.append("<td>30</td>");
        htmlCodigo.append("<td>" + totalCostoEmpaquetado + "</td>");
        htmlCodigo.append("</tr>");
        htmlCodigo.append("<td>Salida</td>");
        htmlCodigo.append("<td>" + salidCosto + "</td>");
        htmlCodigo.append("<td>" + salidaTiempo + "</td>");
        htmlCodigo.append("<td>30</td>");
        htmlCodigo.append("<td>" + totalCostoSalida + "</td>");
        htmlCodigo.append("</tr>");
        htmlCodigo.append("<td>Total</td>");
        htmlCodigo.append("<td></td>");
        htmlCodigo.append("<td></td>");
        htmlCodigo.append("<td></td>");
        htmlCodigo.append("<td>" + totalSumatorio + "</td>");
        htmlCodigo.append("</tr>");
        htmlCodigo.append("</table>");
        htmlCodigo.append("</center>");
        htmlCodigo.append("<h5>Jose Luis Espinoza Jolon</h5>");
        htmlCodigo.append("<h5>202202182</h5>");
        htmlCodigo.append("</body>");
        htmlCodigo.append("</html>");

        try {

            File file = new File("src/ReportesPDF/reporte" + ".html");
            FileWriter fileWriter = new FileWriter(file);
            fileWriter.write(htmlCodigo.toString());
            fileWriter.close();

            Desktop.getDesktop().open(file);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnReporActionPerformed

    public void crearBotonesInventarios() {
        for (int i = 0; i < 30; i++) {
            JButton boton = new JButton(String.valueOf(i + 1));
            listaBotones.add(boton);
            boton.setVisible(true);
            boton.setName("");
            boton.setBackground(Color.WHITE);

            jPInventario.setLayout(new GridLayout(5, 6));
            jPInventario.add(boton);

            Inventario hilo3 = new Inventario(listaBotones, JlConteoInventario);
            InventarioDesapa hilo4 = new InventarioDesapa(listaBotones, JlConteoInventario, JLRepeticiones);
            hilo3.start();
            hilo4.start();

        }

    }

    public void crearBorotonesProduccion() {
        for (int i = 0; i < 30; i++) {
            JButton botones = new JButton(String.valueOf(i + 1));
            listaBotonesProducc.add(botones);
            botones.setVisible(true);
            botones.setName("");
            botones.setBackground(Color.WHITE);

            jPProduccion.setLayout(new GridLayout(5, 6));
            jPProduccion.add(botones);

            Produccion hilo5 = new Produccion(listaBotonesProducc, jLTiempoProduccion, JlConteoInventario, JLRepeticiones);
            ProduccionDespa hilo6 = new ProduccionDespa(listaBotonesProducc, jLTiempoProduccion, JlConteoInventario, JLRepeticiones);
            hilo5.start();
            hilo6.start();

        }

    }

    public void crearBorotonesEmpaquetado() {
        for (int i = 0; i < 30; i++) {
            JButton botones = new JButton(String.valueOf(i + 1));
            listaBotonesEmpaquetado.add(botones);
            botones.setVisible(true);
            botones.setName("");
            botones.setBackground(Color.WHITE);

            jPEmpaquetado.setLayout(new GridLayout(5, 6));
            jPEmpaquetado.add(botones);

            Empaquetado hilo7 = new Empaquetado(listaBotonesEmpaquetado, jLEmpaqueteTiem);
            EmpaqueteDesapa hilo8 = new EmpaqueteDesapa(listaBotonesEmpaquetado, jLEmpaqueteTiem);
            hilo7.start();
            hilo8.start();

        }

    }

    public void crearBorotonesSalida() {
        for (int i = 0; i < 30; i++) {
            JButton botones = new JButton(String.valueOf(i + 1));
            listaBotonesSalida.add(botones);
            botones.setVisible(true);
            botones.setName("");
            botones.setBackground(Color.WHITE);

            jPSalida.setLayout(new GridLayout(5, 6));
            jPSalida.add(botones);

            Salida hilo9 = new Salida(listaBotonesSalida, jLSaliadTiem);
            SalidaDespa hilo10 = new SalidaDespa(listaBotonesSalida, jLSaliadTiem);
            hilo9.start();
            hilo10.start();

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLFinal;
    private javax.swing.JLabel JLRepeticiones;
    private javax.swing.JLabel JlConteoInventario;
    private javax.swing.JButton btnHilo1;
    private javax.swing.JButton btnHiloFinal;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRepor;
    private javax.swing.JLabel jLEmpaqueteTiem;
    private javax.swing.JLabel jLSaliadTiem;
    private javax.swing.JLabel jLTiempoProduccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPEmpaquetado;
    private javax.swing.JPanel jPInventario;
    private javax.swing.JPanel jPProduccion;
    private javax.swing.JPanel jPSalida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel jbTiempo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        jbTiempo.setText((String) arg);
    }
}
